sudo: required
language: bash
services:
  - docker

before_script:
  - docker-compose build . --tag=my-component
script:
  - docker-compose run dev python3 -m 'pytest'
  - docker-compose down
after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
