sudo: required
language: bash
services:
  - docker

before_script:
  - docker build . --tag=my-component
  - docker run -e KBC_EX_CLIENT_ID -e KBC_EX_CLIENT_SECRET -e KBC_EX_REFRESH_TOKEN my-component python3 -m 'pytest'

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
