sudo: required
language: bash
services:
  - docker

before_script:
  - docker build . --tag=my-component
  - docker run my-component python -m 'pytest'

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
