version: '3'
services:
  dev:
    build: .
    image: "pocin/kbc-ex-gmail-attachments:latest"
    tty: true
    stdin_open: true
    command: /bin/sh
    env_file:
      - .env
    volumes:
      - ./:/code
